run:
  timeout: 3m
  tests: true

linters:
  enable:
    - gosimple
    - gofmt
    - errcheck
    - govet
    - staticcheck
    - unused
    - gocritic
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: false
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck